package com.cigna.ctc.apprunner;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "department")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Department {
	@DynamoDBHashKey(attributeName = "departmentId")
	@DynamoDBAutoGeneratedKey
	private String departmentId;

	@DynamoDBAttribute
	private String departmentName;

	@DynamoDBAttribute
	private String departmentAddress;

	@DynamoDBAttribute
	private String departmentCode;
}
